Provide tzdb to Windows build

diff --git a/.github/workflows/tmbasic.yaml b/.github/workflows/tmbasic.yaml
--- a/.github/workflows/tmbasic.yaml
+++ b/.github/workflows/tmbasic.yaml
@@ -82,13 +82,20 @@ jobs:
           IMAGE_NAME=$SYSROOT_IMAGE_NAME ./build.sh
           popd
 
-          # Build the build environment container.
+          # Build the build environment image.
           export IMAGE_NAME="tmbasic-build-env"
           pushd build
           BUILD_ONLY=1 ./${{ matrix.platform }}.sh
           popd
 
-          # Save the build environment container (not just the root filesystem) to a tarball.
+          # For linux-x64 (arbitrary) let's extract the tzdb.dat file to the root directory.
+          # This will be used for the Windows builds because tzdb can't be built on Windows.
+          # Linux/Mac will use the tzdb.tar that's available in their build environment image.
+          if [[ "${{ matrix.platform }}" == "linux-x64" ]]; then
+            NO_BUILD=1 ./${{ matrix.platform }}.sh -c "cp /usr/share/tzdb.tar /code/tzdb.tar"
+          fi
+
+          # Save the build environment image (not just the root filesystem) to a tarball.
           docker save "$IMAGE_NAME" | gzip -c > "tmbasic-build-env-${{ matrix.platform }}.tar.gz"
 
       - name: Upload environment
@@ -96,6 +103,13 @@ jobs:
         with:
           name: ${{ matrix.platform }}
           path: tmbasic-build-env-${{ matrix.platform }}.tar.gz
+
+      - name: Upload tzdb.tar
+        if: matrix.platform == 'linux-x64'
+        uses: actions/upload-artifact@v4
+        with:
+          name: tzdb
+          path: tzdb.tar
 
   build_environment_win:
     name: Build environment (${{ matrix.platform }})
@@ -192,12 +206,18 @@ jobs:
         run: |
           set -euxo pipefail
 
-          # Collect all .tar.gz and .zip files and move them to the root
+          # Collect all .tar, .tar.gz and .zip files and move them to the root
+          find . -type f -name "*.tar" -exec mv {} . \;
           find . -type f -name "*.tar.gz" -exec mv {} . \;
           find . -type f -name "*.zip" -exec mv {} . \;
           ls -lR
 
           # Verify artifacts exist
+          if [ ! -f "tzdb.tar" ]; then
+            echo "Error: tzdb.tar does not exist"
+            exit 1
+          fi
+
           for platform in linux-arm64 linux-arm32 linux-x64 linux-x86 mac-arm64 mac-x64; do
             if [ ! -f "tmbasic-build-env-${platform}.tar.gz" ]; then
               echo "Error: tmbasic-build-env-${platform}.tar.gz does not exist"
@@ -214,6 +234,13 @@ jobs:
 
           # Upload artifacts to R2
           BUILD_ENV_VERSION=$(awk -F= '{ if ($1 == "build-environment") print $2 }' build/build-environment.ini)
+
+          aws s3 cp \
+            --endpoint "$R2_ENDPOINT" \
+            --checksum-algorithm CRC32 \
+            "tzdb.tar" \
+            "s3://tmbasic-archive/tzdb/tzdb-${BUILD_ENV_VERSION}.tar"
+
           for platform in linux-arm64 linux-arm32 linux-x64 linux-x86; do
             aws s3 cp \
               --endpoint "$R2_ENDPOINT" \
@@ -252,6 +279,7 @@ jobs:
             win-x86
             mac-arm64
             mac-x64
+            tzdb
 
   build_tmbasic_linux:
     name: Build (${{ matrix.platform }})
@@ -347,6 +375,10 @@ jobs:
           curl -Lo build-environment.zip "https://tmbasic-archive.com/win-build-envs/tmbasic-build-env-${{ matrix.platform }}-$BUILD_ENV_VERSION.zip"
           unzip build-environment.zip
 
+          # Windows can't build tzdb on its own, so we will grab a prebuilt tar generated by the linux-x64 build env.
+          # We only need it to run the tests. We'll move it into place later when we run the tests.
+          curl -Lo tzdb.tar "https://tmbasic-archive.com/tzdb/tzdb-${BUILD_ENV_VERSION}.tar"
+
       - name: Build
         run: |
           Write-Host "Building environment."
@@ -355,6 +387,9 @@ jobs:
           New-Item -ItemType Directory -Path intermediate
           Move-Item -Path cmake/bin/Release/tmbasic.exe, cmake/bin/Release/runtime*.dat -Destination intermediate
           Compress-Archive -Path "intermediate\*" -DestinationPath "intermediate-${{ matrix.platform }}.zip"
+
+          # Copy tzdb into the executable directory; required for the tests.
+          Copy-Item -Path tzdb.tar -Destination "cmake/bin/Release/tzdb.dat"
 
           # Run x64 and x86 tests, but not arm64 because we have no way to run it.
           $platform = "${{ matrix.platform }}"
